// playgrounds/react/src/App.tsx
import { useMemo, useRef, useState } from 'react'
import chalk from 'chalk'
import {
  useFormatDate,
  useIntersectionObserver,
  useMutationObserver,
  useRerender,
  useResizeObserver,
  useTime,
  useWindowClientRect,
} from '@use-kit/react-hooks'
import { useFetchList } from './hooks'
import './App.css'

function App() {
  const time = useTime()
  const formateDate = useFormatDate()

  const { loading, list } = useFetchList()
  const rect = useWindowClientRect()

  const resizeEl = useRef(null)
  const [text, setText] = useState('')

  useResizeObserver(resizeEl.current, (entries) => {
    const [entry] = entries
    const { width, height } = entry.contentRect
    setText(`width: ${width} height: ${height}`)
  })

  const mutateEl = useRef<HTMLDivElement>(null)

  useMutationObserver(
    mutateEl.current,
    (mutations: MutationRecord[], observer: MutationObserver) => {
      console.log(chalk.green('mutations'), mutations)
      console.log(chalk.green('observer'), observer)
    },
  )

  useMemo(() => {
    setTimeout(() => {
      mutateEl.current?.setAttribute('style', 'color: yellow')

      setTimeout(() => {
        mutateEl.current?.setAttribute('style', '')
      }, 1000)
    }, 1000)
  }, [mutateEl.current])

  const intersectEl = useRef<HTMLDivElement>(null)

  useIntersectionObserver(intersectEl.current as any, (entries: IntersectionObserverEntry[], observer: IntersectionObserver) => {
    console.log(chalk.cyan('entries'), entries)
    console.log(chalk.cyan('observer'), observer)
  })

  const { renderKey, rerender } = useRerender()
  useMemo(() => {
    setTimeout(() => {
      rerender()
      console.log(chalk.red('rerender'))
    }, 2000)
  }, [])

  return (
    <div ref={mutateEl} className="App">
      react test
      <div>time: {time.toString()}</div>
      <div>format: {formateDate}</div>
      <div>request: {loading ? 'Loading...' : list}</div>

      <div>rect width: {rect?.width}</div>
      <textarea ref={resizeEl} disabled rows={3} cols={30} value={text} />

      <div ref={intersectEl} />

      <div key={renderKey} />
    </div>
  )
}

export default App

// playgrounds/vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import chalk from 'chalk'
import {
  useFormatDate,
  useIntersectionObserver,
  useMutationObserver,
  useResizeObserver,
  useRerender,
  useTime,
  useWindowClientRect,
} from '@use-kit/vue-hooks'

import { useFetchList } from './hooks'

const time = useTime()
const format = useFormatDate('YYYY-MM-DD hh:mm:ss a')
const { loading, list } = useFetchList((x: number) => x < 3)
const rect: DOMRect = useWindowClientRect()

const resizeEl = ref<HTMLDivElement>()
const text = ref('')
useResizeObserver(resizeEl, (entries) => {
  const [entry] = entries
  const { width, height } = entry.contentRect
  text.value = `width: ${width} height: ${height}`
})

const mutateEl = ref<HTMLDivElement>()
useMutationObserver(
  mutateEl,
  (mutations: MutationRecord[], observer: MutationObserver) => {
    console.log(chalk.green('mutations'), mutations)
    console.log(chalk.green('observer'), observer)
  },
)

setTimeout(() => {
  mutateEl.value?.setAttribute('style', 'color: yellow')

  setTimeout(() => {
    mutateEl.value?.setAttribute('style', '')
  }, 1000)
}, 1000)

const intersectEl = ref<HTMLDivElement>()
useIntersectionObserver(intersectEl, (entries: IntersectionObserverEntry[], observer: IntersectionObserver) => {
  console.log(chalk.cyan('entries'), entries)
  console.log(chalk.cyan('observer'), observer)
})

const { renderKey, rerender } = useRerender()
setTimeout(() => {
  rerender()
  console.log(chalk.red('rerender'))
}, 2000)
</script>

<template>
  <div ref="mutateEl">
    <div>vue test</div>
    <div>time: {{ time }}</div>
    <div>format: {{ format }}</div>
    <div>request: {{ loading ? 'Loading……' : list }}</div>

    <div>rect width: {{ rect.width }}, rect height: {{ rect.height }}</div>
    <textarea ref="resizeEl" class="resizer" disabled v-text="text" />

    <div ref="intersectEl" />

    <div :key="renderKey" />
  </div>
</template>
